/* jshint node:true */
module.exports = function(grunt) {
	'use strict';

	var path = require('path');

	var basedir = path.dirname(grunt.file.findup('Gruntfile.js'));
	var theme_name = grunt.file.readJSON(path.join(basedir, 'package.json')).name;

	return {
		pkg: grunt.file.readJSON('package.json'),
		uglify: {
			options: {
				screwIE8: true,
			},
			front: {
				src: '<%= pkg.jsLocation %>all.js',
				dest: '<%= pkg.jsLocation %>all.min.js',
			},
			admin: {
				src: '<%= pkg.adminJsLocation %>admin-all.js',
				dest: '<%= pkg.adminJsLocation %>admin-all.min.js',
			},
			customizer_crow: {
				src: '<%= pkg.customizerLocation %>assets/js/color-row.js',
				dest: '<%= pkg.customizerLocation %>assets/js/color-row.min.js',
			},
			customizer_background: {
				src: '<%= pkg.customizerLocation %>assets/js/background.js',
				dest: '<%= pkg.customizerLocation %>assets/js/background.min.js',
			},
			customizer_multicheck: {
				src: '<%= pkg.customizerLocation %>assets/js/multicheck.js',
				dest: '<%= pkg.customizerLocation %>assets/js/multicheck.min.js',
			},
			customizer_typography: {
				src: '<%= pkg.customizerLocation %>assets/js/typography.js',
				dest: '<%= pkg.customizerLocation %>assets/js/typography.min.js',
			},
			customizer_button: {
				src: '<%= pkg.customizerLocation %>assets/js/button.js',
				dest: '<%= pkg.customizerLocation %>assets/js/button.min.js',
			},
			customizer_skins: {
				src: '<%= pkg.customizerLocation %>assets/js/skins.js',
				dest: '<%= pkg.customizerLocation %>assets/js/skins.min.js',
			}
		},
		browserify: {
			customizer_preview: {
				options: {
					transform: [
						["babelify", {
							presets: ["es2015"],
						}]
					]
				},
				files: {
					'<%= pkg.adminJsLocation %>customizer-preview.js': ['<%= pkg.adminJsLocation %>customizer/preview.js'],
				}
			},
			customize_controls_conditionals: {
				options: {
					transform: [
						["babelify", {
							presets: ["es2015"],
						}]
					]
				},
				files: {
					'<%= pkg.adminJsLocation %>customize-controls-conditionals.js': ['<%= pkg.adminJsLocation %>customizer/controls-conditionals.js'],
				}
			},
			customizer_preview_front: {
				options: {
					transform: [
						["babelify", {
							presets: ["es2015"],
						}]
					]
				},
				files: {
					'<%= pkg.adminJsLocation %>customizer-preview-front.js': ['<%= pkg.adminJsLocation %>customizer/preview-front.js'],
				}
			}
		},
		jshint: {
			files: [
				'**/*.js',
				'!**/*.min.js',
				'!documentation/**',
				'!vamtam/plugins/*/**',
				'!style_switcher/**',
				'!vendor/**',
				'!vamtam/assets/js/all.js',
				'!vamtam/assets/js/plugins/thirdparty/**',
				'!vamtam/assets/cubeportfolio/**',
				'!vamtam/redux/extensions/advanced_customizer/**',

				// to be processed by babel
				'!vamtam/admin/assets/js/customizer/**',

				// generated by babel
				'!vamtam/admin/assets/js/customize-controls-conditionals.js',
				'!vamtam/admin/assets/js/customizer-preview-front.js',
				'!vamtam/admin/assets/js/customizer-preview.js',

				'!node_modules/**',
				'!build/**',
				'!dist/**',
				'!utils/grunt/**',
			],
			options: {
				// 'curly': true,
				// 'quotmark': 'single',
				'eqeqeq': true,
				'eqnull': true,
				// 'es3': true,
				'expr': true,
				'immed': true,
				'multistr': true,
				'noarg': true,
				'strict': true,
				'trailing': true,
				'undef': true,
				'unused': true,

				'browser': true,
				'devel': true,

				'globals': {
					'_': false,
					'ajaxurl': false,
					'autosave': false,
					'Backbone': false,
					'colorValidate': false,
					'jQuery': false,
					'Modernizr': false,
					'quicktags': false,
					'RetinaImage': false,
					'RetinaImagePath': false,
					'send_to_editor': false,
					'switchEditors': false,
					'tinyMCE': false,
					'tinymce': false,
					'tinyMCEPreInit': false,
					'vamtam_greensock_wait': false,
					'vamtamgs': false,
					'wp': false,
					'wpActiveEditor': true,
					'VAMTAM_ADMIN': false,
					'VAMTAM_CUSTOMIZE_PREVIEW': false,
					'VAMTAM_FRONT': false,
					'VAMTAM_HIDDEN_WIDGETS': false,
					'vamtam_yepnope': false,
					'VAMTAMED_LANG': false,
					'VamtamTmceShortcodes': false,
				},
			}
		},
		concat: {
			options: {
				separator: '\n',
			},
			dist: {
				src: [
					'<%= pkg.jsLocation %>greensock-loader.js',

					'<%= pkg.jsLocation %>plugins/thirdparty/jquery.imagesloaded.js',
					'<%= pkg.jsLocation %>plugins/thirdparty/jquery.smartresize.js',

					'<%= pkg.jsLocation %>request-animation-frame-polyfill.js',
					'<%= pkg.jsLocation %>media.js',
					'<%= pkg.jsLocation %>lightbox.js',
					'<%= pkg.jsLocation %>tabs-accordions.js',
					'<%= pkg.jsLocation %>menu.js',
					'<%= pkg.jsLocation %>sticky-header.js',
					'<%= pkg.jsLocation %>column-size.js',
					'<%= pkg.jsLocation %>column-animation.js',
					'<%= pkg.jsLocation %>column-progressive-animation.js',
					'<%= pkg.jsLocation %>column-parallax.js',
					'<%= pkg.jsLocation %>general.js',
					'<%= pkg.jsLocation %>splash-screen.js',
					'<%= pkg.jsLocation %>cube.js',
					'<%= pkg.jsLocation %>hide-widgets.js',
					'<%= pkg.jsLocation %>equal-heights.js',
					'<%= pkg.jsLocation %>woocommerce.js',
					'<%= pkg.jsLocation %>portfolio.js',
					'<%= pkg.jsLocation %>ajax-navigation.js',
				],
				dest: '<%= pkg.jsLocation %>all.js',
				nonull: true,
			},
			admin: {
				src: [
					'<%= pkg.adminJsLocation %>plugins/jquery.vamtam.colorpicker.js',
					'<%= pkg.adminJsLocation %>plugins/jquery.vamtam.iconsselector.js',
					'<%= pkg.adminJsLocation %>plugins/jquery.vamtam.backgroundoption.js',
					'<%= pkg.adminJsLocation %>upload.js',
					'<%= pkg.adminJsLocation %>icon-manager.js',
					'<%= pkg.adminJsLocation %>horizontal-blocks.js',
					'<%= pkg.adminJsLocation %>vamtam_admin.js',
					'<%= pkg.adminJsLocation %>post-format-options.js',
				],
				dest: '<%= pkg.adminJsLocation %>admin-all.js',
				nonull: true,
			},
		},
		watch: {
			js: {
				files: [
					'<%= concat.dist.src %>',
					'<%= concat.admin.src %>',
					'<%= uglify.customizer_crow.src %>',
					'<%= uglify.customizer_skins.src %>',
					'<%= uglify.customizer_button.src %>',
					'<%= uglify.customizer_background.src %>',
					'<%= uglify.customizer_multicheck.src %>',
					'<%= uglify.customizer_typography.src %>',
					'<%= pkg.adminJsLocation %>customizer/**',
				],
				tasks: ['buildjs'],
			}
		},
		compress: {
			theme: {
				options: {
					archive: path.join('dist', theme_name + '.zip'),
					mode: 'zip',
					pretty: true
				},
				files: [{
					expand: true,
					src: [
						'**/*',
					],
					cwd: 'build/'
				}]
			}
		},
		makepot: {
			target: {
				options: {
					domainPath: '/languages/',
					exclude: [ 'vamtam/plugins/.*', 'documentation/.*', 'build/.*' ],
					mainFile: 'style.css',
					potFilename: theme_name + '.pot',
					type: 'wp-theme',
					updateTimestamp: true,
				}
			}
		},
		parallel: {
			css: {
				options: {
					stream: true
				},
				tasks: [{
					cmd: 'php',
					args: ['<%= pkg.plessc %>', '-n', '-w', 'vamtam/assets/css/all.less', 'cache/all.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', '-n', '-w', 'vamtam-editor/assets/css/editor.less', 'vamtam-editor/assets/css/editor.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', '-n', '-w', 'vamtam/admin/assets/css/vamtam_admin.less', 'vamtam/admin/assets/css/vamtam_admin.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', '-n', '-w', 'vamtam/admin/assets/css/customizer.less', 'vamtam/admin/assets/css/customizer.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', '-n', '-w', 'vamtam/admin/assets/css/fonts.less', 'vamtam/admin/assets/css/fonts.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', '-n', '-w', '<%= pkg.customizerLocation %>assets/less/color-row.less', '<%= pkg.customizerLocation %>assets/css/color-row.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', '-n', '-w', '<%= pkg.customizerLocation %>assets/less/typography.less', '<%= pkg.customizerLocation %>assets/css/typography.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', '-n', '-w', '<%= pkg.customizerLocation %>assets/less/background.less', '<%= pkg.customizerLocation %>assets/css/background.css']
				}]
			},
			'css-once': {
				options: {
					stream: true
				},
				tasks: [{
					cmd: 'php',
					args: ['<%= pkg.plessc %>', 'vamtam/assets/css/all.less', 'cache/all.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', 'vamtam-editor/assets/css/editor.less', 'vamtam-editor/assets/css/editor.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', 'vamtam/admin/assets/css/vamtam_admin.less', 'vamtam/admin/assets/css/vamtam_admin.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', 'vamtam/admin/assets/css/customizer.less', 'vamtam/admin/assets/css/customizer.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', 'vamtam/admin/assets/css/fonts.less', 'vamtam/admin/assets/css/fonts.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', '<%= pkg.customizerLocation %>assets/less/color-row.less', '<%= pkg.customizerLocation %>assets/css/color-row.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', '<%= pkg.customizerLocation %>assets/less/typography.less', '<%= pkg.customizerLocation %>assets/css/typography.css']
				}, {
					cmd: 'php',
					args: ['<%= pkg.plessc %>', '<%= pkg.customizerLocation %>assets/less/background.less', '<%= pkg.customizerLocation %>assets/css/background.css']
				}]
			},
			dev: {
				options: {
					stream: true
				},
				tasks: [{
					grunt: true,
					args: ['parallel:css'],
				}, {
					grunt: true,
					args: ['watch:js'],
				}]
			},
			composer: {
				options: {
					stream: true
				},
				tasks: [{
					cmd: 'composer',
					args: ['install']
				}]
			},
			'fetch-wp-devel': {
				options: {
					stream: true
				},
				tasks: [{
					cmd: 'svn',
					args: ['co', 'http://develop.svn.wordpress.org/trunk/', path.join('/tmp', 'wp-devel')]
				}]
			},
		},
		clean: {
			build: 'build/',
			dist: 'dist/',
			'post-copy': {
				src: [
					'build/**/vamtam/plugins/**/*',
					'!build/**/vamtam/plugins/*.php',

					'!build/**/vamtam/plugins/foodpress.zip',
					'!build/**/vamtam/plugins/revslider.zip',
					'!build/**/vamtam/plugins/vamtam-twitter.zip',
					'!build/**/vamtam/plugins/vamtam-importers.zip',
					'!build/**/vamtam/plugins/vamtam-elements-a.zip',
					'!build/**/vamtam/plugins/ninja-forms-layout-master.zip',

					'build/**/node_modules',
					'build/**/desktop.ini',
					'build/**/style_switcher',
					'build/**/secrets.json',
				]
			}
		},
		copy: {
			theme: {
				src: '**/*',
				dest: path.join('build', theme_name) + path.sep
			},
			'layerslider-samples': {
				expand: true,
				src: ['**'],
				cwd: 'samples/layerslider/',
				dest: 'vamtam/plugins/layerslider/sampleslider/'
			}
		},
		replace: {
			'style-switcher': {
				options: {
					patterns: [{
						match: /\/\/ @todo remove everything after and including this comment when packaging for sale[\s\S]*/,
						replacement: ''
					}]
				},
				files: [{
					src: [ path.join('build', theme_name, 'functions.php') ],
					dest: path.join('build', theme_name, 'functions.php'),
				}]
			},
			lessc: {
				options: {
					patterns: [{
						match: /lessc/,
						replacement: 'VamtamLessc'
					}]
				},
				files: [{
					src: [ path.join(basedir, 'vamtam', 'classes', 'lessc.php') ],
					dest: path.join(basedir, 'vamtam', 'classes', 'lessc.php'),
				}]
			}
		},
		'add-textdomain': {
			theme: [
				'**/*.php',
				'!vendor/**',
				'!vamtam/plugins/*/**',
				'!node_modules',
			]
		},
		phpcs: {
			application: {
				src: [
					'**/*.php',

					// not used in this theme
					'!vamtam/plugins/vamtam-push-menu/**',
					'!vamtam/plugins/vamtam-sermons/**',
					'!vamtam/plugins/vamtam-scrolling/**',
					'!vamtam/plugins/vamtam-love-it/**',

					'!vamtam/options/help/docs.php',

					'!style_switcher/**',

					// third-party code
					'!vamtam/plugins/layerslider/**',
					'!vamtam/plugins/ninja-forms-layout-master/**',
					'!vamtam/plugins/revslider/**',
					'!vamtam/plugins/foodpress/**',
					'!vamtam/plugins/timetable/**',
					'!vamtam/plugins/vamtam-twitter/lib/**', // this is our plugin, but we use a third-party library for the Twitter API
					'!utils/**',
					'!vendor/**',
					'!vamtam/classes/mobile-detect.php',
					'!vamtam/classes/lessc.php',
					'!vamtam/classes/plugin-activation.php',
					'!vamtam/admin/helpers/updates/class-envato-protected-api.php',
					'!node_modules/**',
					'!**/node_modules/**',
					'!documentation/**',
					'!vamtam/redux/extensions/advanced_customizer/**',
				],
			},
			options: {
				bin: 'phpcs',
				standard: 'vamtam',
				p: true,
				// report: 'summary',
				report: 'full',
			}
		},
		ucss: {
			local: {
				options: {
					// whitelist: [],
					// auth: null
				},
				pages: {
					crawl: 'http://construction.demo.local',
					include: []
				},
				css: ['http://construction.demo.local/wp-content/themes/construction/cache/all.css']
			}
		}
	};
};